version: '3.8'

services:
  auth_db:
    image: postgres:15
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5432:5432"
    volumes:
      - auth_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  orders_db:
    image: postgres:15
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toor
    ports:
      - "5433:5432"
    volumes:
      - orders_db_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_DATABASE: product_db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  auth:
    build: ./services/auth
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql+asyncpg://postgres:toor@auth_db:5432/auth
    depends_on:
      - auth_db
    networks:
      - app-network

  cart:
    build: ./services/cart
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=production
    networks:
      - app-network

  orders:
    build: ./services/orders
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=production
      - DATABASE_URL=postgresql+asyncpg://postgres:toor@orders_db:5432/orders_db
    depends_on:
      - orders_db
    networks:
      - app-network

  products:
    build: ./services/products
    ports:
      - "8003:8003"
    environment:
      - ENVIRONMENT=production
      - MONGODB_URI=mongodb://mongodb:27017/
      - MONGODB_DB_NAME=product_db
      - STATIC_SERVICE_URL=http://statics:8005
    depends_on:
      - mongodb
      - statics
    networks:
      - app-network

  profile:
    build: ./services/profile
    ports:
      - "8004:8004"
    environment:
      - ENVIRONMENT=production
    networks:
      - app-network

  statics:
    build: ./services/statics
    ports:
      - "8005:8005"
    environment:
      - ENVIRONMENT=production
      - HOST=0.0.0.0
      - PORT=8005
      - MAX_FILE_SIZE=5242880
      - ALLOWED_MIME_TYPES=image/jpeg,image/png,image/webp
      - UPLOAD_DIR=/app/static/img
      - METADATA_FILE=/app/metadata.json
    volumes:
      - statics_storage:/app/static
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/nginx.conf:/etc/nginx/nginx.conf
      - statics_storage:/usr/share/nginx/html/static
    depends_on:
      - auth
      - cart
      - orders
      - products
      - profile
      - statics
    networks:
      - app-network

volumes:
  auth_db_data:
  orders_db_data:
  mongodb_data:
  statics_storage:

networks:
  app-network:
    driver: bridge
