version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./auth/app:/app
    networks:
      - app-network

  cart:
    build: ./cart
    ports:
      - "8001:8001"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./cart/app:/app
    networks:
      - app-network

  orders:
    build: ./orders
    ports:
      - "8002:8002"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./orders/app:/app
    networks:
      - app-network

  products:
    build: ./products
    ports:
      - "8003:8003"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./products/app:/app
    networks:
      - app-network

  profile:
    build: ./profile
    ports:
      - "8004:8004"
    environment:
      - ENVIRONMENT=development
    volumes:
      - ./profile/app:/app
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - auth
      - cart
      - orders
      - products
      - profile
    networks:
      - app-network

networks:
  app-network:
    driver: bridge